name       : kotlin
version    : 1.2.31
release    : 1
source: 
    - https://github.com/JetBrains/kotlin/archive/v1.2.31.tar.gz : 5b0ffdbb84c32fc22cc8e01fa029118edae6196f0c3b77bf459fb81de4cea1d2
license    : Apache-2.0
component  : programming
summary    : Multiplatform programming language
description: |
    Kotlin is a statically-typed programming language by JetBrains that runs on the Java virtual machine and also can be transpiled to JavaScript or compiled to native binaries via LLVM.
builddeps  : 
    - openjdk-8
    - apache-ant
rundeps    : 
    - openjdk-8
networking : yes
setup      : |
    echo "
    JAVA_HOME=/usr/lib64/openjdk-8
    JDK_16=/usr/lib64/openjdk-8
    JDK_17=/usr/lib64/openjdk-8
    JDK_18=/usr/lib64/openjdk-8
    " >> gradle.properties
    ant -f update_dependencies.xml
build: |
    export GRADLE_USER_HOME=$HOME
    ./gradlew dist
install: |
    mkdir -p $installdir/usr/share/kotlin/bin $installdir/usr/share/kotlin/lib
    find dist/kotlinc/bin -not -name "*.bat" -exec install -Dm777 {} $installdir/usr/share/kotlin/bin \;
    install -D -m 00777 dist/kotlinc/lib/* $installdir/usr/share/kotlin/lib
    echo %version% > $installdir/usr/share/kotlin/build.txt
    mkdir $installdir/usr/bin
    find $installdir/usr/share/kotlin/bin -type f -not -name "*.bat" -exec sh -c 'ln -sf /usr/share/kotlin/bin/$(basename {}) $installdir/usr/bin/' \;
