name       : kotlin
version    : 1.5.0
release    : 2
source     :
    - https://github.com/JetBrains/kotlin/archive/refs/tags/v1.5.0.tar.gz : 8ad403d161138df39f26f39c546c8e55c3366d73e86ba67ec8fe00d920e69c11
license    : Apache-2.0
component  : programming
homepage   : https://kotlinlang.org/
summary    : Statically typed multiplatform programming language
description: |
    Kotlin is a modern, concise, and safe programming language by JetBrains. It can run on the Java virtual machine, can be transpiled to JavaScript, and can be compiled to native binaries via LLVM. This package contains the JVM and JS compilers.
builddeps  :
    - openjdk-8
    - gradle
rundeps    :
    - openjdk-11
networking : yes
setup      : |
    %patch -p1 < $pkgfiles/fix-resolution-ambiguity-with-gradle-6-8.patch
    rm -f $workdir/gradle/verification-metadata*.xml
build      : |
    export GRADLE_USER_HOME=$workdir/.gradle_home
    export JAVA_HOME="/usr/lib64/openjdk-11"
    export JDK_16="/usr/lib64/openjdk-8"
    export JDK_17="/usr/lib64/openjdk-8"
    export JDK_18="/usr/lib64/openjdk-8"
    export JDK_9="/usr/lib64/openjdk-11"

    gradle dist \
        --no-daemon \
        --parallel \
        --stacktrace \
        -PdeployVersion="%version%" \
        -Pteamcity=true
install    : |
    install -dm 00644 $installdir/usr/share/kotlin/lib
    install -Dm 00644 $workdir/dist/kotlinc/lib/* $installdir/usr/share/kotlin/lib

    rm $workdir/dist/kotlinc/bin/*.bat

    install -dm 00755 $installdir/usr/share/kotlin/bin
    install -Dm 00755 $workdir/dist/kotlinc/bin/* $installdir/usr/share/kotlin/bin
    sed -i "11r $pkgfiles/java-shim.txt" $installdir/usr/share/kotlin/bin/kotlinc

    install -dm 00755 $installdir/usr/bin
    for FILE in $(basename -a $installdir/usr/share/kotlin/bin/*); do
        ln -s /usr/share/kotlin/bin/$FILE $installdir/usr/bin/$FILE
    done
